# # Java Gradle CircleCI 2.0 configuration file
# #
# # Check https://circleci.com/docs/2.0/language-java/ for more details
# #
# version: 2
# jobs:
#   build:
#     docker:
#       # specify the version you desire here
#       - image: circleci/openjdk:8-jdk
      
#       # Specify service dependencies here if necessary
#       # CircleCI maintains a library of pre-built images
#       # documented at https://circleci.com/docs/2.0/circleci-images/
#       # - image: circleci/postgres:9.4

#     working_directory: ~/repo

#     environment:
#       # Customize the JVM maximum heap limit
#       JVM_OPTS: -Xmx3200m
#       TERM: dumb
    
#     steps:
#       - checkout

#       # Download and cache dependencies
#       - restore_cache:
#           keys:
#           - v1-dependencies-{{ checksum "build.gradle" }}
#           # fallback to using the latest cache if no exact match is found
#           - v1-dependencies-

#       - run: gradle dependencies

#       - save_cache:
#           paths:
#             - ~/.gradle
#           key: v1-dependencies-{{ checksum "build.gradle" }}
        
#       # run tests!
#       - run: gradle test

version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
        command: /sbin/init
#       - image: circleci/android:api-25-alpha
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      ANDROID_HOME: /usr/local/android-sdk-linux
      GRADLE_OPTS: -Xmx1024m -XX:MaxPermSize=1024m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run: |-
        echo y | android update sdk --no-ui --all --filter "tools"
        echo y | /usr/local/android-sdk-linux/tools/bin/sdkmanager "platform-tools" "platforms;android-27" "platforms;android-26" "platforms;android-25" "platforms;android-24" "build-tools;27.0.3" "build-tools;27.0.2" "build-tools;27.0.0" "build-tools;25.0.2" "build-tools;25.0.0"

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
